import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { Header, Footer } from "@/components/layout";
import Providers from "@/components/providers/Provider";

const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "My Store • A fashion shop brings you the best collection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${bricolage.variable} antialiased`}
      >
        <Providers>
          <Header hiddenAt="/setup-password" />
          {children}
          <Footer hiddenAt="/setup-password" />
        </Providers>
      </body>
    </html>
  );
}
