import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { Header, Footer } from "@/components/layout";
import Providers from "@/components/providers/Provider";
import { Suspense } from "react";
import { Spinner } from "@/components/styled";

const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "My Store • A fashion shop brings you the best collection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${bricolage.variable} antialiased`}
      >
        <Suspense fallback={<Spinner />}>
          <Providers>
            <Header hiddenAt={["/setup-password", "/vendor"]}  />
            {children}
            <Footer hiddenAt={["/setup-password", "/vendor"]} />
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
